package com.example

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.widget.Toast
import androidx.compose.animation.AnimatedVisibility
import androidx.compose.animation.animateColorAsState
import androidx.compose.animation.fadeIn
import androidx.compose.animation.fadeOut
import androidx.compose.animation.shrinkVertically
import androidx.compose.animation.slideInVertically
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.Image
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.draw.scale
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.itemsIndexed
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Clear
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.ImeAction
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import kotlinx.coroutines.launch

// Frosted Glass Premium Theme Design (Emerald Green & Mint palette with glassmorphism panels)
private val BrandDarkBg = Color(0xFF070B08)
private val BrandGlassSurface = Color(0x0CFFFFFF)     // Extra thin translucent glass (5% white opacity)
private val BrandGlassSurfaceSelected = Color(0x3310B981) // Soft neon emerald highlight overlay
private val BrandGlassBorder = Color(0x0DFFFFFF)      // Ultra-delicate translucent border
private val BrandGlassBorderSelected = Color(0x7F34D399) // Vivid glow emerald/mint border for active items
private val BrandGreenAccent = Color(0xFF10B981)      // Emerald-500
private val BrandMintAccent = Color(0xFF34D399)       // Mint/Emerald-400
private val BrandMutedText = Color(0xFF94A3B8)         // Slate-400 for highly polished text
private val BrandLightBg = Color(0xFFF8FAFC)           // White/slate for contrast button

@OptIn(ExperimentalLayoutApi::class)
@Composable
fun PlaylistGeneratorScreen(viewModel: PlaylistViewModel) {
    val context = LocalContext.current
    val coroutineScope = rememberCoroutineScope()

    val selectedTab by viewModel.selectedTab.collectAsState()
    val selectedTheme by viewModel.selectedTheme.collectAsState()
    val songTitle by viewModel.songTitle.collectAsState()
    val artistName by viewModel.artistName.collectAsState()
    val selectedGenre by viewModel.selectedGenre.collectAsState()
    val hours by viewModel.hours.collectAsState()
    val minutes by viewModel.minutes.collectAsState()
    val isNoLimit by viewModel.isNoLimit.collectAsState()
    val generatedPlaylist by viewModel.generatedPlaylist.collectAsState()
    val hasGenerated by viewModel.hasGenerated.collectAsState()
    val errorMsg by viewModel.errorMsg.collectAsState()
    val autoDetectedGenre by viewModel.autoDetectedGenre.collectAsState()
    val isLoading by viewModel.isLoading.collectAsState()
    val playlistSource by viewModel.playlistSource.collectAsState()

    var updateInfo by remember { mutableStateOf<UpdateChecker.UpdateInfo?>(null) }
    var showUpdateDialog by remember { mutableStateOf(false) }

    LaunchedEffect(Unit) {
        val info = UpdateChecker.checkForUpdate(currentVersionCode = 1)
        if (info.hasUpdate) {
            updateInfo = info
            showUpdateDialog = true
        }
    }

    if (showUpdateDialog && updateInfo != null) {
        AlertDialog(
            onDismissRequest = { showUpdateDialog = false },
            title = {
                Text(
                    text = "Mise à jour disponible !",
                    color = Color.White,
                    fontWeight = FontWeight.Bold
                )
            },
            text = {
                Text(
                    text = "Voulez-vous télécharger la nouvelle version de MixFlow (v${updateInfo?.versionName}) ?",
                    color = Color(0xFFE2E8F0)
                )
            },
            confirmButton = {
                Button(
                    onClick = {
                        showUpdateDialog = false
                        try {
                            val intent = android.content.Intent(
                                android.content.Intent.ACTION_VIEW,
                                android.net.Uri.parse(updateInfo?.downloadUrl ?: "")
                            ).apply {
                                addFlags(android.content.Intent.FLAG_ACTIVITY_NEW_TASK)
                            }
                            context.startActivity(intent)
                        } catch (e: Exception) {
                            Toast.makeText(context, "Impossible d'ouvrir l'URL de téléchargement", Toast.LENGTH_LONG).show()
                        }
                    },
                    colors = ButtonDefaults.buttonColors(
                        containerColor = Color(0xFF10B981),
                        contentColor = Color.White
                    )
                ) {
                    Text("Mettre à jour")
                }
            },
            dismissButton = {
                TextButton(
                    onClick = { showUpdateDialog = false }
                ) {
                    Text("Plus tard", color = Color(0xFF94A3B8))
                }
            },
            containerColor = Color(0xFF0F172A),
            tonalElevation = 6.dp
        )
    }

    // Screen Layout
    Scaffold(
        modifier = Modifier.fillMaxSize().testTag("playlist_maker_screen"),
        contentWindowInsets = WindowInsets.safeDrawing
    ) { innerPadding ->
        Box(
            modifier = Modifier
                .fillMaxSize()
                .background(
                    Brush.verticalGradient(
                        colors = listOf(BrandDarkBg, Color(0xFF040B06), Color(0xFF0C1D13))
                    )
                )
                .padding(innerPadding)
        ) {
            LazyColumn(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(horizontal = 20.dp),
                contentPadding = PaddingValues(top = 22.dp, bottom = 40.dp),
                verticalArrangement = Arrangement.spacedBy(18.dp)
            ) {
                // Header Branding with Glass Logo Accent
                item {
                    Row(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(vertical = 12.dp),
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.SpaceBetween
                    ) {
                        Row(
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            // Growing Launcher App Logo Image
                            Image(
                                painter = painterResource(id = R.drawable.mix_flow_logo_1779778550377),
                                contentDescription = "Logo MixFlow",
                                modifier = Modifier
                                    .size(42.dp)
                                    .clip(RoundedCornerShape(10.dp))
                            )
                            Spacer(modifier = Modifier.width(12.dp))
                            Column {
                                Row(verticalAlignment = Alignment.CenterVertically) {
                                    Text(
                                        text = "MixFlow",
                                        fontSize = 24.sp,
                                        fontWeight = FontWeight.Black,
                                        color = Color.White,
                                        fontFamily = FontFamily.SansSerif,
                                        modifier = Modifier.testTag("app_title")
                                    )
                                    Spacer(modifier = Modifier.width(6.dp))
                                    Box(
                                        modifier = Modifier
                                            .clip(RoundedCornerShape(12.dp))
                                            .background(Color(0x3310B981))
                                            .border(1.dp, Color(0x3334D399), RoundedCornerShape(12.dp))
                                            .padding(horizontal = 8.dp, vertical = 2.dp)
                                    ) {
                                        Text(
                                            text = "PWA",
                                            color = Color(0xFFD1FAE5),
                                            fontSize = 9.sp,
                                            fontWeight = FontWeight.Black
                                        )
                                    }
                                }
                                Text(
                                    text = "Smart Playlist • Solver Hors-ligne",
                                    fontSize = 11.sp,
                                    color = BrandMutedText,
                                    fontWeight = FontWeight.Medium
                                )
                            }
                        }

                        // Little decorative plus button mimicking active/inactive
                        Box(
                            modifier = Modifier
                                .size(36.dp)
                                .clip(CircleShape)
                                .background(BrandGlassSurface)
                                .border(1.dp, BrandGlassBorder, CircleShape)
                                .clickable {
                                    Toast.makeText(context, "Saisissez les critères pour générer !", Toast.LENGTH_SHORT).show()
                                },
                            contentAlignment = Alignment.Center
                        ) {
                            Text(
                                text = "+",
                                color = Color.White,
                                fontSize = 16.sp,
                                fontWeight = FontWeight.Bold
                            )
                        }
                    }
                }

                // Modern Tab Swapper (Glassmorphic Segmented Control)
                item {
                    Row(
                        modifier = Modifier
                            .fillMaxWidth()
                            .clip(RoundedCornerShape(16.dp))
                            .background(BrandGlassSurface)
                            .border(1.dp, BrandGlassBorder, RoundedCornerShape(16.dp))
                            .padding(4.dp),
                        horizontalArrangement = Arrangement.spacedBy(4.dp)
                    ) {
                        val tabs = listOf(
                            "🎤 Par référence" to 0,
                            "✨ Par thème" to 1
                        )
                        tabs.forEach { (text, index) ->
                            val isSelected = selectedTab == index
                            val itemBg by animateColorAsState(
                                targetValue = if (isSelected) BrandGreenAccent else Color.Transparent
                            )
                            val textColor by animateColorAsState(
                                targetValue = if (isSelected) Color.White else BrandMutedText
                            )
                            Box(
                                modifier = Modifier
                                    .weight(1f)
                                    .clip(RoundedCornerShape(12.dp))
                                    .background(itemBg)
                                    .clickable { viewModel.selectTab(index) }
                                    .padding(vertical = 12.dp)
                                    .testTag("tab_button_$index"),
                                contentAlignment = Alignment.Center
                            ) {
                                Text(
                                    text = text,
                                    color = textColor,
                                    fontSize = 13.sp,
                                    fontWeight = FontWeight.Black
                                )
                            }
                        }
                    }
                }

                // Section 1: Music Base Search (Song / Artist) configured with Frosted Glass Panels
                if (selectedTab == 0) {
                    item {
                        Card(
                            modifier = Modifier.fillMaxWidth(),
                            colors = CardDefaults.cardColors(containerColor = BrandGlassSurface),
                            border = BorderStroke(1.dp, BrandGlassBorder),
                            shape = RoundedCornerShape(24.dp)
                        ) {
                        Column(
                            modifier = Modifier.padding(20.dp)
                        ) {
                            Text(
                                text = "1. Musique de référence (Optionnel)",
                                color = Color.White,
                                fontSize = 14.sp,
                                fontWeight = FontWeight.ExtraBold,
                                modifier = Modifier.padding(bottom = 14.dp)
                            )

                            // Title Field with custom frosted style inputs
                            OutlinedTextField(
                                value = songTitle,
                                onValueChange = { viewModel.updateSongTitle(it) },
                                label = { Text("Titre de la musique", color = BrandMutedText) },
                                singleLine = true,
                                keyboardOptions = KeyboardOptions(imeAction = ImeAction.Next),
                                colors = OutlinedTextFieldDefaults.colors(
                                    focusedTextColor = Color.White,
                                    unfocusedTextColor = Color.White,
                                    focusedBorderColor = BrandGreenAccent,
                                    unfocusedBorderColor = BrandGlassBorder,
                                    focusedContainerColor = Color(0x1A000000),
                                    unfocusedContainerColor = Color(0x1A000000)
                                ),
                                trailingIcon = {
                                    if (songTitle.isNotEmpty()) {
                                        IconButton(onClick = { viewModel.updateSongTitle("") }) {
                                            Icon(Icons.Default.Clear, contentDescription = "Effacer", tint = BrandMutedText)
                                        }
                                    }
                                },
                                shape = RoundedCornerShape(14.dp),
                                modifier = Modifier.fillMaxWidth().testTag("song_title_input")
                            )

                            Spacer(modifier = Modifier.height(14.dp))

                            // Artist Field with matching style
                            OutlinedTextField(
                                value = artistName,
                                onValueChange = { viewModel.updateArtistName(it) },
                                label = { Text("Artiste / Groupe", color = BrandMutedText) },
                                singleLine = true,
                                keyboardOptions = KeyboardOptions(imeAction = ImeAction.Done),
                                colors = OutlinedTextFieldDefaults.colors(
                                    focusedTextColor = Color.White,
                                    unfocusedTextColor = Color.White,
                                    focusedBorderColor = BrandGreenAccent,
                                    unfocusedBorderColor = BrandGlassBorder,
                                    focusedContainerColor = Color(0x1A000000),
                                    unfocusedContainerColor = Color(0x1A000000)
                                ),
                                trailingIcon = {
                                    if (artistName.isNotEmpty()) {
                                        IconButton(onClick = { viewModel.updateArtistName("") }) {
                                            Icon(Icons.Default.Clear, contentDescription = "Effacer", tint = BrandMutedText)
                                        }
                                    }
                                },
                                shape = RoundedCornerShape(14.dp),
                                modifier = Modifier.fillMaxWidth().testTag("artist_input")
                            )

                            // Real-time automatic genre detection notifier (beautiful purple/gray bubble)
                            AnimatedVisibility(
                                visible = autoDetectedGenre != null,
                                enter = slideInVertically() + fadeIn(),
                                exit = shrinkVertically() + fadeOut()
                            ) {
                                autoDetectedGenre?.let { detected ->
                                    Row(
                                        verticalAlignment = Alignment.CenterVertically,
                                        modifier = Modifier
                                            .padding(top = 14.dp)
                                            .fillMaxWidth()
                                            .clip(RoundedCornerShape(10.dp))
                                            .background(BrandGreenAccent.copy(alpha = 0.15f))
                                            .border(1.dp, BrandGreenAccent.copy(alpha = 0.3f), RoundedCornerShape(10.dp))
                                            .padding(horizontal = 12.dp, vertical = 8.dp)
                                    ) {
                                        Text(
                                            text = "✨ Style identifié :",
                                            fontSize = 11.sp,
                                            color = Color(0xFFA7F3D0),
                                            fontWeight = FontWeight.Bold
                                        )
                                        Spacer(modifier = Modifier.width(6.dp))
                                        Text(
                                            text = detected,
                                            fontSize = 12.sp,
                                            color = Color.White,
                                            fontWeight = FontWeight.ExtraBold,
                                            modifier = Modifier.testTag("detected_genre_label")
                                        )
                                    }
                                }
                            }
                        }
                    }
                }
                } // Close if (selectedTab == 0) for Section 1

                // Section 2: Choose music style with aesthetic Glass selection chips
                if (selectedTab == 0) {
                    item {
                        Card(
                            modifier = Modifier.fillMaxWidth(),
                            colors = CardDefaults.cardColors(containerColor = BrandGlassSurface),
                            border = BorderStroke(1.dp, BrandGlassBorder),
                            shape = RoundedCornerShape(24.dp)
                        ) {
                        Column(
                            modifier = Modifier.padding(20.dp)
                        ) {
                            Text(
                                text = "2. Sélectionner le genre musical",
                                color = Color.White,
                                fontSize = 14.sp,
                                fontWeight = FontWeight.ExtraBold,
                                modifier = Modifier.padding(bottom = 14.dp)
                            )

                            FlowRow(
                                modifier = Modifier.fillMaxWidth(),
                                horizontalArrangement = Arrangement.spacedBy(8.dp),
                                verticalArrangement = Arrangement.spacedBy(8.dp)
                            ) {
                                viewModel.availableGenres.forEach { genre ->
                                    val isSelected = selectedGenre == genre
                                    val chipBg by animateColorAsState(
                                        targetValue = if (isSelected) BrandGreenAccent else Color(0x13FFFFFF)
                                    )
                                    val chipBorderColor by animateColorAsState(
                                        targetValue = if (isSelected) BrandGreenAccent else BrandGlassBorder
                                    )
                                    val chipTextColor by animateColorAsState(
                                        targetValue = if (isSelected) Color.White else Color(0xFFCBD5E1)
                                    )

                                    Box(
                                        modifier = Modifier
                                            .clip(RoundedCornerShape(32.dp))
                                            .background(chipBg)
                                            .border(1.dp, chipBorderColor, RoundedCornerShape(32.dp))
                                            .clickable { viewModel.selectGenre(genre) }
                                            .padding(horizontal = 14.dp, vertical = 8.dp)
                                            .testTag("genre_chip_$genre"),
                                        contentAlignment = Alignment.Center
                                    ) {
                                        Text(
                                            text = genre,
                                            fontSize = 12.sp,
                                            fontWeight = if (isSelected) FontWeight.Black else FontWeight.Medium,
                                            color = chipTextColor
                                        )
                                    }
                                }
                            }
                        }
                    }
                }
                } // Close if (selectedTab == 0) for Section 2

                // Section 1 (Tab 1): Choose Theme with beautiful Emoji selectors
                if (selectedTab == 1) {
                    item {
                        Card(
                            modifier = Modifier.fillMaxWidth(),
                            colors = CardDefaults.cardColors(containerColor = BrandGlassSurface),
                            border = BorderStroke(1.dp, BrandGlassBorder),
                            shape = RoundedCornerShape(24.dp)
                        ) {
                            Column(
                                modifier = Modifier.padding(20.dp)
                            ) {
                                Text(
                                    text = "1. Choisir un thème de playlist",
                                    color = Color.White,
                                    fontSize = 14.sp,
                                    fontWeight = FontWeight.ExtraBold,
                                    modifier = Modifier.padding(bottom = 14.dp)
                                )

                                FlowRow(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.spacedBy(8.dp),
                                    verticalArrangement = Arrangement.spacedBy(8.dp)
                                ) {
                                    viewModel.availableThemes.forEach { theme ->
                                        val isSelected = selectedTheme == theme
                                        val chipBg by animateColorAsState(
                                            targetValue = if (isSelected) BrandGreenAccent else Color(0x13FFFFFF)
                                        )
                                        val chipBorderColor by animateColorAsState(
                                            targetValue = if (isSelected) BrandGreenAccent else BrandGlassBorder
                                        )
                                        val chipTextColor by animateColorAsState(
                                            targetValue = if (isSelected) Color.White else Color(0xFFCBD5E1)
                                        )

                                        val emoji = when (theme) {
                                            "Chill / Détente" -> "🏝️"
                                            "Sport / Dynamique" -> "⚡"
                                            "Soirée / Fête" -> "🎉"
                                            "Focus / Concentration" -> "🧠"
                                            "Voyage / Road Trip" -> "🚗"
                                            "Romantique" -> "💖"
                                            "Nostalgique / Rétro" -> "📜"
                                            else -> "✨"
                                        }

                                        Box(
                                            modifier = Modifier
                                                .clip(RoundedCornerShape(32.dp))
                                                .background(chipBg)
                                                .border(1.dp, chipBorderColor, RoundedCornerShape(32.dp))
                                                .clickable { viewModel.selectTheme(theme) }
                                                .padding(horizontal = 14.dp, vertical = 8.dp)
                                                .testTag("theme_chip_$theme"),
                                            contentAlignment = Alignment.Center
                                        ) {
                                            Row(
                                                verticalAlignment = Alignment.CenterVertically,
                                                horizontalArrangement = Arrangement.Center
                                            ) {
                                                Text(
                                                    text = "$emoji ",
                                                    fontSize = 14.sp
                                                )
                                                Text(
                                                    text = theme,
                                                    fontSize = 12.sp,
                                                    fontWeight = if (isSelected) FontWeight.Black else FontWeight.Medium,
                                                    color = chipTextColor
                                                )
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }

                // Section 3: Time limitation ("Je m'en fiche" toggle) configured with subtle styling
                item {
                    Card(
                        modifier = Modifier.fillMaxWidth(),
                        colors = CardDefaults.cardColors(containerColor = BrandGlassSurface),
                        border = BorderStroke(1.dp, BrandGlassBorder),
                        shape = RoundedCornerShape(24.dp)
                    ) {
                        Column(
                            modifier = Modifier.padding(20.dp)
                        ) {
                            Row(
                                modifier = Modifier.fillMaxWidth(),
                                horizontalArrangement = Arrangement.SpaceBetween,
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                Text(
                                    text = if (selectedTab == 0) "3. Durée de la playlist" else "2. Durée de la playlist",
                                    color = Color.White,
                                    fontSize = 14.sp,
                                    fontWeight = FontWeight.ExtraBold
                                )

                                // "Je m'en fiche" toggle styled in Emerald Green glow
                                Row(
                                    verticalAlignment = Alignment.CenterVertically,
                                    modifier = Modifier
                                        .clip(RoundedCornerShape(12.dp))
                                        .clickable { viewModel.toggleNoLimit(!isNoLimit) }
                                        .padding(horizontal = 4.dp, vertical = 4.dp)
                                ) {
                                    Text(
                                        text = "Je m'en fiche",
                                        color = if (isNoLimit) BrandGreenAccent else BrandMutedText,
                                        fontSize = 12.sp,
                                        fontWeight = FontWeight.Bold,
                                        modifier = Modifier.padding(end = 6.dp)
                                    )
                                    Switch(
                                        checked = isNoLimit,
                                        onCheckedChange = { viewModel.toggleNoLimit(it) },
                                        colors = SwitchDefaults.colors(
                                            checkedThumbColor = Color.White,
                                            checkedTrackColor = BrandGreenAccent,
                                            uncheckedThumbColor = BrandMutedText,
                                            uncheckedTrackColor = Color(0x1FEEF2F6)
                                        ),
                                        modifier = Modifier.scale(0.85f).testTag("no_limit_switch")
                                    )
                                }
                            }

                            Spacer(modifier = Modifier.height(14.dp))

                            // Custom designed Inputs columns
                            val fieldAlpha = if (isNoLimit) 0.35f else 1.0f
                            Row(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .padding(vertical = 4.dp),
                                horizontalArrangement = Arrangement.spacedBy(16.dp)
                            ) {
                                OutlinedTextField(
                                    value = if (isNoLimit) "" else hours,
                                    onValueChange = { viewModel.updateHours(it) },
                                    enabled = !isNoLimit,
                                    label = { Text("Heures", color = BrandMutedText.copy(alpha = fieldAlpha)) },
                                    placeholder = { Text("0", color = BrandMutedText.copy(alpha = 0.5f)) },
                                    singleLine = true,
                                    keyboardOptions = KeyboardOptions(
                                        keyboardType = KeyboardType.Number,
                                        imeAction = ImeAction.Next
                                    ),
                                    colors = OutlinedTextFieldDefaults.colors(
                                        focusedTextColor = Color.White.copy(alpha = fieldAlpha),
                                        unfocusedTextColor = Color.White.copy(alpha = fieldAlpha),
                                        disabledTextColor = Color.White.copy(alpha = fieldAlpha),
                                        focusedBorderColor = BrandGreenAccent,
                                        unfocusedBorderColor = BrandGlassBorder,
                                        disabledBorderColor = BrandGlassBorder.copy(alpha = fieldAlpha),
                                        focusedContainerColor = Color(0x1A000000),
                                        unfocusedContainerColor = Color(0x1A000000),
                                        disabledContainerColor = Color(0x0D000000)
                                    ),
                                    shape = RoundedCornerShape(14.dp),
                                    modifier = Modifier
                                        .weight(1f)
                                        .testTag("hours_input")
                                )

                                OutlinedTextField(
                                    value = if (isNoLimit) "" else minutes,
                                    onValueChange = { viewModel.updateMinutes(it) },
                                    enabled = !isNoLimit,
                                    label = { Text("Minutes", color = BrandMutedText.copy(alpha = fieldAlpha)) },
                                    placeholder = { Text("30", color = BrandMutedText.copy(alpha = 0.5f)) },
                                    singleLine = true,
                                    keyboardOptions = KeyboardOptions(
                                        keyboardType = KeyboardType.Number,
                                        imeAction = ImeAction.Done
                                    ),
                                    colors = OutlinedTextFieldDefaults.colors(
                                        focusedTextColor = Color.White.copy(alpha = fieldAlpha),
                                        unfocusedTextColor = Color.White.copy(alpha = fieldAlpha),
                                        disabledTextColor = Color.White.copy(alpha = fieldAlpha),
                                        focusedBorderColor = BrandGreenAccent,
                                        unfocusedBorderColor = BrandGlassBorder,
                                        disabledBorderColor = BrandGlassBorder.copy(alpha = fieldAlpha),
                                        focusedContainerColor = Color(0x1A000000),
                                        unfocusedContainerColor = Color(0x1A000000),
                                        disabledContainerColor = Color(0x0D000000)
                                    ),
                                    shape = RoundedCornerShape(14.dp),
                                    modifier = Modifier
                                        .weight(1f)
                                        .testTag("minutes_input")
                                )
                            }
                        }
                    }
                }

                // Error Message Display
                errorMsg?.let { error ->
                    item {
                        Box(
                            modifier = Modifier
                                .fillMaxWidth()
                                .clip(RoundedCornerShape(14.dp))
                                .background(Color(0xFFEF4444).copy(alpha = 0.15f))
                                .border(1.dp, Color(0xFFEF4444).copy(alpha = 0.4f), RoundedCornerShape(14.dp))
                                .padding(16.dp)
                        ) {
                            Text(
                                text = error,
                                color = Color(0xFFFCA5A5),
                                fontSize = 13.sp,
                                fontWeight = FontWeight.Bold,
                                modifier = Modifier.testTag("error_label")
                            )
                        }
                    }
                }

                // Submit Button styled with deep emerald/mint linear gradient & glass shadow
                item {
                    val buttonEnabled = !isLoading
                    Button(
                        onClick = { viewModel.generatePlaylist() },
                        enabled = buttonEnabled,
                        colors = ButtonDefaults.buttonColors(
                            containerColor = Color.Transparent,
                            disabledContainerColor = Color.Transparent
                        ),
                        contentPadding = PaddingValues(),
                        shape = RoundedCornerShape(16.dp),
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(58.dp)
                            .border(width = 0.dp, color = Color.Transparent)
                            .testTag("generate_button")
                    ) {
                        Box(
                            modifier = Modifier
                                .fillMaxSize()
                                .background(
                                    Brush.horizontalGradient(
                                        colors = if (buttonEnabled) {
                                            listOf(BrandGreenAccent, BrandMintAccent)
                                        } else {
                                            listOf(BrandGreenAccent.copy(alpha = 0.5f), BrandMintAccent.copy(alpha = 0.5f))
                                        }
                                    )
                                ),
                            contentAlignment = Alignment.Center
                        ) {
                            if (isLoading) {
                                Row(
                                    verticalAlignment = Alignment.CenterVertically,
                                    horizontalArrangement = Arrangement.Center
                                ) {
                                    CircularProgressIndicator(
                                        color = Color.White,
                                        strokeWidth = 2.5.dp,
                                        modifier = Modifier.size(22.dp)
                                    )
                                    Spacer(modifier = Modifier.width(12.dp))
                                    Text(
                                        text = "RECHERCHE & CALCUL...",
                                        color = Color.White,
                                        letterSpacing = 1.2.sp,
                                        fontWeight = FontWeight.Black,
                                        fontSize = 14.sp
                                    )
                                }
                            } else {
                                Text(
                                    text = "GÉNÉRER LA PLAYLIST",
                                    color = Color.White,
                                    letterSpacing = 1.2.sp,
                                    fontWeight = FontWeight.Black,
                                    fontSize = 15.sp
                                )
                            }
                        }
                    }
                }

                // Section 4: Results Showcase with high fidelity frosted paneling
                if (hasGenerated) {
                    item {
                        Column(
                            verticalArrangement = Arrangement.spacedBy(14.dp),
                            modifier = Modifier
                                .fillMaxWidth()
                                .padding(top = 10.dp)
                        ) {
                            val totalDurationSec = generatedPlaylist.sumOf { it.durationSeconds }
                            val formattedDuration = formatCumulativeDuration(totalDurationSec)

                            // Glass stats banner
                            Card(
                                modifier = Modifier.fillMaxWidth(),
                                colors = CardDefaults.cardColors(containerColor = BrandGlassSurface),
                                border = BorderStroke(1.dp, BrandGreenAccent.copy(alpha = 0.35f)),
                                shape = RoundedCornerShape(24.dp)
                            ) {
                                Row(
                                    modifier = Modifier
                                        .fillMaxWidth()
                                        .padding(20.dp),
                                    verticalAlignment = Alignment.CenterVertically,
                                    horizontalArrangement = Arrangement.SpaceBetween
                                  ) {
                                    Column(modifier = Modifier.weight(1f)) {
                                        Text(
                                            text = "PLAYLIST SUGGÉRÉE",
                                            color = Color(0xFFA7F3D0),
                                            fontSize = 11.sp,
                                            fontWeight = FontWeight.Black,
                                            letterSpacing = 1.sp
                                        )
                                        Spacer(modifier = Modifier.height(6.dp))

                                        playlistSource?.let { src ->
                                            val isOnline = src == "INTERNET"
                                            val emoji = if (isOnline) "🌐" else "📦"
                                            val textLabel = if (isOnline) "Source : Internet (Temps réel)" else "Source : Catalogue Local (Hors-ligne)"
                                            val bg = if (isOnline) Color(0x2A10B981) else Color(0x2A6F7C8F)
                                            val border = if (isOnline) Color(0x6610B981) else Color(0x666F7C8F)
                                            val txt = if (isOnline) Color(0xFF34D399) else Color(0xFF94A3B8)

                                            Box(
                                                modifier = Modifier
                                                    .padding(bottom = 8.dp)
                                                    .clip(RoundedCornerShape(8.dp))
                                                    .background(bg)
                                                    .border(1.dp, border, RoundedCornerShape(8.dp))
                                                    .padding(horizontal = 8.dp, vertical = 4.dp)
                                                    .testTag("source_badge")
                                            ) {
                                                Row(
                                                    verticalAlignment = Alignment.CenterVertically,
                                                    horizontalArrangement = Arrangement.Center
                                                ) {
                                                    Text(text = emoji, fontSize = 10.sp)
                                                    Spacer(modifier = Modifier.width(4.dp))
                                                    Text(
                                                        text = textLabel,
                                                        color = txt,
                                                        fontSize = 10.sp,
                                                        fontWeight = FontWeight.Bold
                                                    )
                                                }
                                            }
                                        }

                                        Text(
                                            text = formattedDuration,
                                            color = Color.White,
                                            fontSize = 22.sp,
                                            fontWeight = FontWeight.Black,
                                            modifier = Modifier.testTag("playlist_total_duration")
                                        )
                                        Text(
                                            text = "${generatedPlaylist.size} titres sélectionnés",
                                            color = BrandMutedText,
                                            fontSize = 13.sp,
                                            fontWeight = FontWeight.Bold,
                                            modifier = Modifier.testTag("playlist_total_count")
                                        )
                                    }

                                    // Copier la playlist tactile button with classic modern solid light contrast
                                    Button(
                                        onClick = {
                                            if (generatedPlaylist.isEmpty()) {
                                                Toast.makeText(context, "La playlist est vide !", Toast.LENGTH_SHORT).show()
                                                return@Button
                                            }
                                            val textToCopy = formatPlaylistToText(
                                                if (selectedTab == 0) selectedGenre else selectedTheme, 
                                                generatedPlaylist, 
                                                formattedDuration
                                            )
                                            val clipboard = context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
                                            val clip = ClipData.newPlainText("Spotify Playlist", textToCopy)
                                            clipboard.setPrimaryClip(clip)
                                            Toast.makeText(context, "📋 Playlist copiée dans le presse-papiers !", Toast.LENGTH_LONG).show()
                                        },
                                        colors = ButtonDefaults.buttonColors(containerColor = BrandLightBg),
                                        shape = RoundedCornerShape(16.dp),
                                        contentPadding = PaddingValues(horizontal = 18.dp, vertical = 10.dp),
                                        modifier = Modifier
                                            .height(48.dp)
                                            .testTag("copy_button")
                                    ) {
                                        Row(
                                            verticalAlignment = Alignment.CenterVertically,
                                            horizontalArrangement = Arrangement.Center
                                        ) {
                                            Text(
                                                text = "Copier",
                                                color = Color.Black,
                                                fontWeight = FontWeight.Black,
                                                fontSize = 13.sp
                                            )
                                        }
                                    }
                                }
                            }
                        }
                    }

                    // Individual Track Items
                    if (generatedPlaylist.isEmpty()) {
                        item {
                            Box(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .padding(vertical = 40.dp),
                                contentAlignment = Alignment.Center
                            ) {
                                Text(
                                    text = "Aucun titre trouvé dans cette catégorie.",
                                    color = BrandMutedText,
                                    fontSize = 14.sp
                                )
                            }
                        }
                    } else {
                        itemsIndexed(generatedPlaylist) { index, track ->
                            TrackResultRow(index + 1, track)
                        }
                    }
                }
            }
        }
    }
}

@Composable
fun TrackResultRow(index: Int, track: Track) {
    Card(
        modifier = Modifier
            .fillMaxWidth()
            .padding(vertical = 3.dp)
            .testTag("track_item_$index"),
        colors = CardDefaults.cardColors(containerColor = BrandGlassSurface),
        border = BorderStroke(1.dp, BrandGlassBorder),
        shape = RoundedCornerShape(18.dp)
    ) {
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = 14.dp, vertical = 12.dp),
            verticalAlignment = Alignment.CenterVertically
        ) {
            // Index number styled beautifully with neon glowing backdrops
            Box(
                modifier = Modifier
                    .size(38.dp)
                    .clip(RoundedCornerShape(10.dp))
                    .background(Color(0x13FFFFFF))
                    .border(1.dp, BrandGlassBorder, RoundedCornerShape(10.dp)),
                contentAlignment = Alignment.Center
            ) {
                Text(
                    text = "$index",
                    color = Color.White,
                    fontWeight = FontWeight.Black,
                    fontSize = 13.sp
                )
            }

            Spacer(modifier = Modifier.width(14.dp))

            // Title & Artist
            Column(
                modifier = Modifier.weight(1.0f)
            ) {
                Text(
                    text = track.title,
                    color = Color.White,
                    fontSize = 14.sp,
                    fontWeight = FontWeight.ExtraBold,
                    maxLines = 1,
                    overflow = TextOverflow.Ellipsis
                )
                Spacer(modifier = Modifier.height(2.dp))
                Row(
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Text(
                        text = track.artist,
                        color = BrandMutedText,
                        fontSize = 12.sp,
                        fontWeight = FontWeight.Bold,
                        maxLines = 1,
                        overflow = TextOverflow.Ellipsis,
                        modifier = Modifier.weight(1f, fill = false)
                    )
                    Spacer(modifier = Modifier.width(10.dp))
                    
                    // Genre badge of track (styled as glass element)
                    Box(
                        modifier = Modifier
                            .clip(RoundedCornerShape(6.dp))
                            .background(Color(0x3310B981))
                            .padding(horizontal = 8.dp, vertical = 3.dp)
                    ) {
                        Text(
                            text = track.genre,
                            color = Color(0xFFA7F3D0),
                            fontSize = 8.sp,
                            fontWeight = FontWeight.Black
                        )
                    }
                }
            }

            Spacer(modifier = Modifier.width(8.dp))

            // Duration
            Text(
                text = formatDuration(track.durationSeconds),
                color = Color.White,
                fontSize = 13.sp,
                fontWeight = FontWeight.Bold
            )
        }
    }
}

// Format cumulative duration into French text eg "1 h 12 min" or "45 min 20 s"
private fun formatCumulativeDuration(seconds: Int): String {
    val h = seconds / 3600
    val m = (seconds % 3600) / 60
    val s = seconds % 60
    
    return when {
         h > 0 -> "${h}h ${m}m"
         m > 0 -> "${m}m ${s}s"
         else -> "${s}s"
    }
}

// Format track individual duration into standard MM:SS
private fun formatDuration(seconds: Int): String {
    val m = seconds / 60
    val s = seconds % 60
    return String.format("%d:%02d", m, s)
}

// Plain text playlist builder to export to Spotify/Notes
private fun formatPlaylistToText(genre: String, list: List<Track>, stats: String): String {
    val sb = java.lang.StringBuilder()
    sb.append("🎵 Ma Smart Playlist MixFlow - [$genre] ✨\n")
    sb.append("📊 Durée : $stats | ${list.size} titres\n")
    sb.append("----------------------------\n")
    list.forEachIndexed { index, track ->
        sb.append(String.format("%02d. %s - %s (%s)\n", index + 1, track.title, track.artist, formatDuration(track.durationSeconds)))
    }
    sb.append("----------------------------\n")
    sb.append("Créé avec MixFlow (Local Solver Offline)")
    return sb.toString()
}


